/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Currency = { 'EUR' : null } |
  { 'GBP' : null } |
  { 'KES' : null } |
  { 'MWK' : null } |
  { 'TZS' : null } |
  { 'UGX' : null } |
  { 'USD' : null } |
  { 'ZAR' : null } |
  { 'ZMW' : null };
export type Principal = Principal;
export interface Profile {
  'username' : string,
  'balance' : bigint,
  'walletAddress' : string,
  'email' : string,
}
export interface ProfileUpdate {
  'username' : string,
  'walletAddress' : string,
  'email' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustUserBalance' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmDeposit' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTotalMemberCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'initiateDeposit' : ActorMethod<[Currency, bigint], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAdminDeposit' : ActorMethod<[Currency, bigint], bigint>,
  'recordWin' : ActorMethod<[Principal, bigint], undefined>,
  'releaseWinningsToUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[ProfileUpdate], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];